In [178]:
import torch
import numpy as np
import matplotlib.pyplot as plt

## Initialising Tensor

In [179]:
x = torch.ones(3,2)
print(x)
x = torch.zeros(3,2)
print(x)
x = torch.randn(3,2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[ 0.1874,  1.0313],
        [-0.9141,  0.9917],
        [ 0.4011,  0.8744]])


In [180]:
x = torch.empty(3,2)
print(x)
y = torch.zeros_like(x)
print(y)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [181]:
x = torch.linspace(0,1,5)
print(x)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [182]:
x = torch.tensor([[1,2],
                 [3,4],
                 [5,6]])
print(x)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


## Tensor slicing

In [183]:
print(x.size())
print(x[ :, 1])
print(x[0, : ])

torch.Size([3, 2])
tensor([2, 4, 6])
tensor([1, 2])


In [184]:
y = x[1,1]
print(y)
print(y.item())

tensor(4)
4


## Reshaping Tensors

In [185]:
print(x)
y = x.view(2,3)
print(y)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [186]:
y = x.view(6,-1)
print(y)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


## Tensor Operation

In [187]:
x = torch.ones(3,2)
y = torch.ones(3,2)
z = x+y
print(z)
z = x-y
print(z)
z = x*y
print(z)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [188]:
z = y.add(x)
print(y)
print(z)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


In [189]:
z = y.add_(x)
print(y)
print(z)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


## Numpy <> Pytorch

In [190]:
x_np = x.numpy()
print(type(x),type(x_np))
print(x_np)

<class 'torch.Tensor'> <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [191]:
a = np.random.randn(5)
print(a)
a_pt = torch.from_numpy(a)
print(type(a),type(a_pt))
print(a_pt)

[ 0.502422    0.50189887 -0.4800962  -0.21468825 -0.27801622]
<class 'numpy.ndarray'> <class 'torch.Tensor'>
tensor([ 0.5024,  0.5019, -0.4801, -0.2147, -0.2780], dtype=torch.float64)


In [192]:
np.add(a,1,out=a)
print(a)
print(a_pt)

[1.502422   1.50189887 0.5199038  0.78531175 0.72198378]
tensor([1.5024, 1.5019, 0.5199, 0.7853, 0.7220], dtype=torch.float64)


In [193]:
%%time
for i in range(10):
    a = np.random.randn(1000,1000)
    b = np.random.randn(1000,1000)
    c = np.matmul(a,b)

CPU times: user 4.57 s, sys: 580 ms, total: 5.15 s
Wall time: 706 ms


In [194]:
%%time
for i in range(10):
    a = torch.randn([1000,1000])
    b = torch.randn([1000,1000])
    c = np.matmul(a,b)

CPU times: user 2.66 s, sys: 321 ms, total: 2.98 s
Wall time: 404 ms


## GPU Pytorch

In [195]:
print("Is MPS available: ", torch.backends.mps.is_available())

Is MPS available:  True


In [196]:
if torch.backends.mps.is_available():
    print("MPS is available on this system.")
else:
    print("MPS is not available on this system.")

MPS is available on this system.


In [197]:
%%time
if torch.backends.mps.is_available():
    device = torch.device("mps")
    print("mps is available and will be used")
else:
    device = torch.device("cpu")
    print("mps device is not available")

for i in range(10):
    a = torch.randn([1000,1000],device=device)
    b = torch.randn([1000,1000],device=device)
    c = torch.matmul(a,b)

mps is available and will be used
CPU times: user 149 ms, sys: 17.7 ms, total: 167 ms
Wall time: 26.2 ms


## Autograd

In [198]:
x = torch.ones([3,2],requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)


In [199]:
y = x+5
print(y)

tensor([[6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)


In [200]:
z = y*y+1
print(z)

tensor([[37., 37.],
        [37., 37.],
        [37., 37.]], grad_fn=<AddBackward0>)


In [201]:
t = torch.sum(z)
print(t)

tensor(222., grad_fn=<SumBackward0>)


In [202]:
t.backward()

In [203]:
print(x.grad)

tensor([[12., 12.],
        [12., 12.],
        [12., 12.]])


In [204]:
x = torch.ones([3,2],requires_grad=True)
y = x+5
z = 1/(1+torch.exp(-y))
print(z)
s = torch.sum(z)
s.backward()
print(x.grad)

tensor([[0.9975, 0.9975],
        [0.9975, 0.9975],
        [0.9975, 0.9975]], grad_fn=<MulBackward0>)
tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


## Example

In [205]:
x = torch.randn([20,1],requires_grad=True)
y = 3*x - 2
print(y)

tensor([[-4.7360],
        [ 2.3941],
        [-2.5474],
        [-1.7888],
        [ 0.2680],
        [-5.2091],
        [-2.7009],
        [-0.6364],
        [-5.1564],
        [-0.1234],
        [-6.7188],
        [-5.9030],
        [-2.2234],
        [ 0.1378],
        [-0.4374],
        [-1.4577],
        [ 2.5696],
        [ 3.3935],
        [ 2.2239],
        [ 0.6721]], grad_fn=<SubBackward0>)


In [206]:
w = torch.tensor([1.],requires_grad=True)
b = torch.tensor([1.],requires_grad=True)
y_hat = w*x + b
print(y_hat)

tensor([[ 0.0880],
        [ 2.4647],
        [ 0.8175],
        [ 1.0704],
        [ 1.7560],
        [-0.0697],
        [ 0.7664],
        [ 1.4545],
        [-0.0521],
        [ 1.6255],
        [-0.5729],
        [-0.3010],
        [ 0.9255],
        [ 1.7126],
        [ 1.5209],
        [ 1.1808],
        [ 2.5232],
        [ 2.7978],
        [ 2.4080],
        [ 1.8907]], grad_fn=<AddBackward0>)


In [207]:
loss = torch.sum((y_hat - y)**2)
print(loss)

tensor(211.1302, grad_fn=<SumBackward0>)


In [208]:
loss.backward()
print(w.grad,b.grad)

tensor([-55.1704]) tensor([103.9732])


In [210]:
learning_rate = 0.01
w = torch.tensor([1.],requires_grad=True)
b = torch.tensor([1.],requires_grad=True)
print(w.item(),b.item())
for i in range(10):
    x = torch.randn([20,1])
    y = 3*x-2
    y_hat = w*x + b
    loss = torch.sum((y_hat-y)**2)
    loss.backward()
    with torch.no_grad():
        w -= learning_rate*w.grad
        b -= learning_rate*b.grad
        w.grad.zero_()
        b.grad.zero_()
    print(w.item(),b.item())

1.0 1.0
1.5644917488098145 -0.26060378551483154
2.124390125274658 -0.9803071618080139
2.372218370437622 -1.3721275329589844
2.7009477615356445 -1.6302838325500488
2.788274049758911 -1.7583967447280884
2.9243390560150146 -1.8989534378051758
2.9780125617980957 -1.9493839740753174
2.9992847442626953 -1.972229242324829
2.99955153465271 -1.983339786529541
2.9984781742095947 -1.9899698495864868


In [222]:
%%time
learning_rate = 0.001
N = 1000
epochs = 2000
w = torch.randn([N],requires_grad=True)
b = torch.randn([1],requires_grad=True)
print(torch.mean(w).item(),b.item())
for i in range(epochs):
    x = torch.randn([N])
    y = torch.dot(3*torch.ones([N]),x)-2
    y_hat = torch.dot(w,x)+b
    loss = torch.sum((y_hat-y)**2)
    loss.backward()
    with torch.no_grad():
        w -= learning_rate*w.grad
        b -= learning_rate*b.grad
        w.grad.zero_()
        b.grad.zero_()
    print(torch.mean(w).item(),b.item())

-0.07765831798315048 0.001967376796528697
-0.053515903651714325 0.3802892863750458
-0.05348090082406998 0.3212909698486328
-0.05250418558716774 0.215981125831604
-0.036517996340990067 0.5460574626922607
-0.030649051070213318 0.6849406957626343
-0.028948970139026642 0.7399774789810181
-0.0256675835698843 0.8610200881958008
-0.023981433361768723 0.7213417291641235
0.023498481139540672 0.17115122079849243
0.030046559870243073 -0.029818862676620483
0.03115418180823326 -0.09560772031545639
0.03336296230554581 -0.2687603831291199
0.03336666524410248 -0.26819682121276855
0.0353100411593914 -0.16546034812927246
0.04729001224040985 0.10454931855201721
0.050655949860811234 0.22109344601631165
0.05916646122932434 0.01966911554336548
0.061034880578517914 0.1551295816898346
0.06121890991926193 0.1713588833808899
0.06453760713338852 0.2928675711154938
0.06611001491546631 0.22408056259155273
0.07221343368291855 0.4212694764137268
0.0724191889166832 0.439314067363739
0.07886205613613129 0.208087444305

In [223]:
%%time
if torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")

learning_rate = 0.001
N = 1000
epochs = 2000
w = torch.randn([N],requires_grad=True,device=device)
b = torch.randn([1],requires_grad=True,device=device)
print(torch.mean(w).item(),b.item())
for i in range(epochs):
    x = torch.randn([N],device=device)
    y = torch.dot(3*torch.ones([N],device=device),x)-2
    y_hat = torch.dot(w,x)+b
    loss = torch.sum((y_hat-y)**2)
    loss.backward()
    with torch.no_grad():
        w -= learning_rate*w.grad
        b -= learning_rate*b.grad
        w.grad.zero_()
        b.grad.zero_()
    print(torch.mean(w).item(),b.item())

-0.05032341927289963 0.9328334927558899
-0.04041406512260437 0.6548326015472412
-0.035181958228349686 0.8168080449104309
-0.03455688804388046 0.8509902358055115
-0.026288779452443123 1.0757144689559937
-0.026452764868736267 1.0920745134353638
-0.025024965405464172 1.1686244010925293
-0.013525117188692093 1.4959282875061035
0.017932550981640816 1.9204764366149902
0.02763032726943493 1.6555702686309814
0.02763727493584156 1.6592543125152588
0.04211656004190445 1.9525032043457031
0.04222561791539192 2.1573243141174316
0.056365787982940674 2.4756221771240234
0.05635970085859299 2.460007905960083
0.057687416672706604 2.3651130199432373
0.09047863632440567 2.736333131790161
0.09058429300785065 2.8078532218933105
0.10923945158720016 3.116471529006958
0.10937847197055817 3.143980026245117
0.13009028136730194 3.5019712448120117
0.1310020089149475 3.5347378253936768
0.13152502477169037 3.5787243843078613
0.1317879557609558 3.6101131439208984
0.1337611824274063 3.4475340843200684
0.13596862554550